concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "nonroot"
  url = "http://localhost:10080/"
  token = "6AP6SvE8cA9uYkt4N3Nx"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/users/pgolard/gcloud/pj-becfr-eagle-ingestion-dev1-sa-sapimingestion-dev.json"
    [runners.cache.azure]

[[runners]]
  name = "macos runner with docker executor"
  url = "http://localhost:10080/"
  token = "6DSzD4PZbMas-zdozhar"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/users/pgolard/gcloud/pj-becfr-eagle-ingestion-dev1-sa-sapimingestion-dev.json"
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "macos runner docker executor"
  url = "http://localhost:10080/"
  token = "vPRWiyUvhQsaVKiSxXW9"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/users/pgolard/gcloud/pj-becfr-eagle-ingestion-dev1-sa-sapimingestion-dev.json"
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "macos runner docker executor with aliased hostname"
  url = "http://gitlab:10080/"
  token = "g94o98VbTJpP9XXEU448"
  executor = "docker"
  clone_url = "http://172.18.0.2:80"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/users/pgolard/gcloud/pj-becfr-eagle-ingestion-dev1-sa-sapimingestion-dev.json"
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode="gitlab-docker_default"

[[runners]]
  name = "docker mac local et hosts"
  url = "http://gitlab:10080"
  token = "QaDx3xryfVyow-b61KV5"
  executor = "docker"
  clone_url = "http://172.18.0.2:80"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
      CredentialsFile = "/users/pgolard/gcloud/pj-becfr-eagle-ingestion-dev1-sa-sapimingestion-dev.json"
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:2.6"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mode="gitlab-docker_default"
